### ISSUE TITLE
Apply rice

### ISSUE THREAD

**Issue by 3dgoose** [MobSenpai/sugoi#2]
Admitting I have cloned the repo and copied files in .config, how to apply rice and change background ?

**Comment by mobsenpai** [comment]
> Admitting I have cloned the repo and copied files in .config, how to apply rice and change background ?

                                            🇭​​​​​🇪​​​​​🇱​​​​​🇱​​​​​🇴​​​​​

First of all I am really sorry for the late reply, was out of station. Did you make it work? I am not really using this myself nowadays but it should work if you have installed awesome-git version and copied all the files to .config/awesome, after that read the readme for stuff like terminal and other stuff so that you don't get stuck upon login. I doubt you are still interested in this lol :). but you can also dm me through element(matrix) `@mobsenpai:matrix.org`
